#!/usr/bin/env bash
#configures the ngix to redirect for /redirect_me
echo "301"
new_location="server {\n\t
        listen 80 default_server;\n\t
        listen [::]:80 default_server;\n\t
        root /var/www/html;\n\t
        index index.html index.htm index.nginx-debian.html;\n\t
        server_name _;\n\t

        location / {\n\t
                # First attempt to serve request as file, then\n\t\t
                # as directory, then fall back to displaying a 404.\n\t\t
                try_files \$uri \$uri/ =404;\n\t
        }\n\t
        location /redirect_me {\n\t\t
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t
        }\n
}"
sudo echo -e "$new_location" | sudo tee /etc/nginx/sites-enabled/default > /dev/null 2>&1
sudo ssh -i ~/.ssh/school ubuntu@100.27.10.6 './3-redirection'
sudo service nginx restart
