#!/usr/bin/env bash
#change the 404 file
new_location="server {\n\t
        listen 80 default_server;\n\t
        listen [::]:80 default_server;\n\t
        root /var/www/html;\n\t
        index index.html index.htm index.nginx-debian.html;\n\t
        server_name _;\n\t

        location / {\n\t
                # First attempt to serve request as file, then\n\t\t
                # as directory, then fall back to displaying a 404.\n\t\t
                return 404 'Ceci n\'est pas une page\n\n';
        }\n\t
        location /redirect_me {\n\t\t
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t
        }\n
}"
sudo echo -e $new_location | sudo tee /etc/nginx/sites-enabled/default > /dev/null 2>&1
sudo nginx -s reload
