#!/usr/bin/env bash
#configure the new server
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee  /var/www/html/404.html
new_location="server {\n\t
        listen 80 default_server;\n\t
        listen [::]:80 default_server;\n\t
        root /var/www/html;\n\t
	error_page 404 /404.html;\n\t
        index index.html index.htm index.nginx-debian.html;\n\t
        server_name _;\n\t
        location = /404.html{\n\t\t
                root /var/www/html;\n\t\t
                internal;\n\t
        }\n\t
        location / {\n\t
                # First attempt to serve request as file, then\n\t\t
                # as directory, then fall back to displaying a 404.\n\t\t
          	add_header X-Served-By $HOSTNAME;
        }\n
        location /redirect_me {\n\t\t
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t
        }\n
}"
echo -e "$new_location" | sudo tee /etc/nginx/sites-enabled/default > /dev/null 2>&1
sudo service nginx restart
