#!/usr/bin/env bash
#what’s keeping your Ubuntu container’s Nginx inst on port 80
file="server {\n\t
	listen 80 default_server;\n\t
       	listen [::]:80 default_server;\n\t
	root /var/www/html;\n\t
	index index.html index.htm index.nginx-debian.html;\n\t
	server_name _;\n\t
	location / {\n\t\t
		try_files $uri $uri/ =404;\n\t
	}\n
}
"
echo -e $file | sudo tee /etc/nginx/sites-enabled/default > /dev/null
sudo service nginx restart
